import { describe, expect, test } from "bun:test"
import { Effect, Exit, Layer, Schema } from "effect"
import { HttpClient, HttpClientRequest, HttpClientResponse } from "effect/unstable/http"
import { testEffect } from "../lib/effect"

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Build a POST request following the same pattern as the prod
 * `postJson` helper in symphony.ts.
 */
function buildPost(url: string, body?: unknown, token?: string) {
  let req = HttpClientRequest.post(url).pipe(HttpClientRequest.acceptJson)
  if (body !== undefined) req = req.pipe(HttpClientRequest.bodyJsonUnsafe(body))
  if (token) req = req.pipe(HttpClientRequest.bearerToken(token))
  return req
}

/** Decode the JSON body from a constructed HttpClientRequest. */
const decodeBody = (req: HttpClientRequest.HttpClientRequest) =>
  HttpClientRequest.toWeb(req).pipe(
    Effect.flatMap((r) => Effect.tryPromise(() => r.clone().text())),
    Effect.map(JSON.parse),
  )

// ---------------------------------------------------------------------------
// Mock HTTP layers
// ---------------------------------------------------------------------------

type Capture = { url: string; method: string }
const captures: Capture[] = []

const mockOk = HttpClient.make((request) => {
  captures.push({ url: request.url, method: request.method })
  return Effect.succeed(
    HttpClientResponse.fromWeb(
      request,
      new Response(JSON.stringify({ html_url: "https://github.com/o/r/pulls/1" }), {
        status: 200,
        headers: { "Content-Type": "application/json" },
      }),
    ),
  )
})

const mockNotFound = HttpClient.make(() =>
  Effect.succeed(
    HttpClientResponse.fromWeb({} as any, new Response("Not Found", { status: 404 })),
  ),
)

const mockOkLayer = Layer.succeed(HttpClient.HttpClient, mockOk)
const mockNotFoundLayer = Layer.succeed(HttpClient.HttpClient, mockNotFound)

const itOk = testEffect(mockOkLayer)
const it404 = testEffect(mockNotFoundLayer)

// ---------------------------------------------------------------------------
// Request structure
// ---------------------------------------------------------------------------

describe("GitHub API request structure", () => {
  test("createGithubPR: POST /repos/{o}/{r}/pulls with correct body", async () => {
    const url = "https://api.github.com/repos/owner/repo/pulls"
    const req = buildPost(url, {
      title: "[Symphony] Add login feature",
      head: "feature/login",
      base: "main",
      body: "This PR was automatically generated by Symphony to address: Add login feature",
      maintainer_can_modify: true,
    }, "ghp_token123")

    const web = await Effect.runPromise(HttpClientRequest.toWeb(req))

    expect(web.method).toBe("POST")
    expect(web.url).toBe(url)
    expect(web.headers.get("authorization")).toBe("Bearer ghp_token123")
    expect(web.headers.get("accept")).toBe("application/json")

    const json = JSON.parse(await web.clone().text())
    expect(json.title).toBe("[Symphony] Add login feature")
    expect(json.head).toBe("feature/login")
    expect(json.base).toBe("main")
    expect(json.maintainer_can_modify).toBe(true)
  })

  test("addIssueComment: POST /repos/{o}/{r}/issues/{n}/comments with comment body", async () => {
    const url = "https://api.github.com/repos/owner/repo/issues/42/comments"
    const req = buildPost(url, {
      body: "✅ A pull request has been created for this issue: https://github.com/owner/repo/pulls/1",
    })

    const web = await Effect.runPromise(HttpClientRequest.toWeb(req))

    expect(web.method).toBe("POST")
    expect(web.url).toBe(url)
    const json = JSON.parse(await web.clone().text())
    expect(json.body).toContain("pull request has been created")
  })

  test("closeIssue: POST with state:closed and state_reason:completed", async () => {
    const url = "https://api.github.com/repos/owner/repo/issues/42"
    const req = buildPost(url, {
      state: "closed",
      state_reason: "completed",
    })

    const web = await Effect.runPromise(HttpClientRequest.toWeb(req))

    expect(web.method).toBe("POST")
    expect(web.url).toBe(url)
    const json = JSON.parse(await web.clone().text())
    expect(json.state).toBe("closed")
    expect(json.state_reason).toBe("completed")
  })

  test("no auth header when token is undefined", async () => {
    const req = buildPost("https://api.github.com/repos/owner/repo/pulls", {
      title: "[Symphony] No auth",
      head: "branch",
      base: "main",
    })
    const web = await Effect.runPromise(HttpClientRequest.toWeb(req))
    expect(web.headers.get("authorization")).toBeNull()
  })

  test("createGithubPR body with long bodyText truncation", async () => {
    const longText = "x".repeat(200)
    const req = buildPost("https://api.github.com/repos/o/r/pulls", {
      title: "[Symphony] T",
      head: "b",
      base: "main",
      body: `This PR was automatically generated by Symphony based on issue #${longText.slice(0, 80)}...\n\n${longText}`,
      maintainer_can_modify: true,
    })

    const json = await Effect.runPromise(decodeBody(req))
    expect(json.body).toContain("based on issue #")
    expect(json.body.length).toBeGreaterThan(100)
  })
})

// ---------------------------------------------------------------------------
// Response handling
// ---------------------------------------------------------------------------

describe("GitHub API response handling", () => {
  itOk.live("parses html_url from 200 response", () =>
    Effect.gen(function* () {
      captures.length = 0
      const http = yield* HttpClient.HttpClient
      const req = buildPost("https://api.github.com/repos/owner/repo/pulls", {
        title: "[Symphony] T",
        head: "b",
        base: "main",
        maintainer_can_modify: true,
      })

      const httpOk = HttpClient.filterStatusOk(http)
      const response = yield* httpOk.execute(req)
      const data = yield* HttpClientResponse.schemaBodyJson(
        Schema.Struct({ html_url: Schema.String }),
      )(response)

      expect(data.html_url).toBe("https://github.com/o/r/pulls/1")
      expect(captures[0].url).toContain("/repos/owner/repo/pulls")
      expect(captures[0].method).toBe("POST")
    }),
  )

  it404.live("rejects non-2xx status code via filterStatusOk", () =>
    Effect.gen(function* () {
      const http = yield* HttpClient.HttpClient
      const req = buildPost("https://api.github.com/repos/owner/repo/issues/999", {
        state: "closed",
        state_reason: "completed",
      })

      const httpOk = HttpClient.filterStatusOk(http)
      const exit = yield* httpOk.execute(req).pipe(Effect.exit)

      expect(Exit.isFailure(exit)).toBe(true)
    }),
  )

  itOk.live("createGithubPR returns html_url string from response", () =>
    Effect.gen(function* () {
      const http = yield* HttpClient.HttpClient
      const req = buildPost("https://api.github.com/repos/owner/repo/pulls", {
        title: "[Symphony] Return URL",
        head: "b",
        base: "main",
        maintainer_can_modify: true,
      })

      const httpOk = HttpClient.filterStatusOk(http)
      const response = yield* httpOk.execute(req)
      const data = yield* HttpClientResponse.schemaBodyJson(
        Schema.Struct({ html_url: Schema.String }),
      )(response)

      expect(typeof data.html_url).toBe("string")
      expect(data.html_url).toMatch(/^https?:\/\//)
    }),
  )
})
